services:
  - mssql2012sp1

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:

    - PYTHON_VERSION: 3.5-x64
      MINICONDA: C:\Miniconda35-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:

  # Install Python (from the official .msi of http://python.org) and pip when
  # Previous line gives error in conda
  - powershell .\\appveyor\\install.ps1

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # We need wheel installed to build wheels
  - "conda install wheel --yes"

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture

  #- "%CMD_IN_ENV% pip install -r dev-requirements.txt"
  # Install in order of list in dev-requirements.txt
  #- "cat dev-requirements.txt | xargs -n 1 -L 1 conda install --yes"
  # Use conda environment defined by environment.yml
  - "conda env create"
  - "activate hcconda"

build_script:
  # Upload mdf and ldf file for integration tests
  - ps: iex .\appveyor\CIBuild_DBCreate.ps1
  # Build the compiled extension
  #- "%CMD_IN_ENV% python setup.py build"
  - "python setup.py build"
  - "python setup.py install"

test_script:
  # From here: https://github.com/rmcgibbo/python-appveyor-conda-example/blob/master/appveyor.yml

  # TODO: set up conda build to compliment setup.py build above
  #- "conda install conda-build --yes"
  #- "conda build conda-recipe --quiet"

  # Run the project tests
  - python setup.py nosetests"

after_test:
  # If tests are successful, create binary packages for the project.
  - "python setup.py bdist_wheel"
  - "python setup.py bdist_wininst"
  - "python setup.py bdist_msi"
  - "python setup.py bdist --format=zip"
  - "python setup.py bdist --format=gztar"
  
  - ps: "ls dist"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#
