name: hcconda
channels: !!python/tuple
- defaults
dependencies:
- _license=1.1=py35_1
- _nb_ext_conf=0.3.0=py35_0
- alabaster=0.7.9=py35_0
- anaconda-clean=1.0.0=py35_0
- anaconda-client=1.5.1=py35_0
- anaconda=custom=py35_0
- anaconda-navigator=1.3.1=py35_0
- argcomplete=1.0.0=py35_1
- astroid=1.4.7=py35_0
- astropy=1.2.1=np111py35_0
- babel=2.3.4=py35_0
- backports=1.0=py35_0
- beautifulsoup4=4.5.1=py35_0
- bitarray=0.8.1=py35_1
- blaze=0.10.1=py35_0
- bokeh=0.12.2=py35_0
- boto=2.42.0=py35_0
- bottleneck=1.1.0=np111py35_0
- bzip2=1.0.6=vc14_3
- cffi=1.7.0=py35_0
- chest=0.2.3=py35_0
- click=6.6=py35_0
- cloudpickle=0.2.1=py35_0
- clyent=1.2.2=py35_0
- colorama=0.3.7=py35_0
- comtypes=1.1.2=py35_0
- configobj=5.0.6=py35_0
- console_shortcut=0.1.1=py35_1
- contextlib2=0.5.3=py35_0
- cryptography=1.5=py35_0
- curl=7.49.0=vc14_0
- cycler=0.10.0=py35_0
- cython=0.24.1=py35_0
- cytoolz=0.8.0=py35_0
- dask=0.11.0=py35_0
- datashape=0.5.2=py35_0
- decorator=4.0.10=py35_0
- dill=0.2.5=py35_0
- docutils=0.12=py35_2
- dynd-python=0.7.2=py35_0
- entrypoints=0.2.2=py35_0
- et_xmlfile=1.0.1=py35_0
- fastcache=1.0.2=py35_1
- filelock=2.0.6=py35_0
- flask=0.11.1=py35_0
- flask-cors=2.1.2=py35_0
- freetype=2.5.5=vc14_1
- get_terminal_size=1.0.0=py35_0
- gevent=1.1.2=py35_0
- greenlet=0.4.10=py35_0
- h5py=2.6.0=np111py35_2
- hdf5=1.8.15.1=vc14_4
- heapdict=1.0.0=py35_1
- icu=57.1=vc14_0
- idna=2.1=py35_0
- imagesize=0.7.1=py35_0
- ipykernel=4.5.0=py35_0
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_0
- itsdangerous=0.24=py35_0
- jdcal=1.2=py35_1
- jedi=0.9.0=py35_1
- jinja2=2.8=py35_1
- jpeg=8d=vc14_2
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.0=py35_0
- lazy-object-proxy=1.2.1=py35_0
- libdynd=0.7.2=0
- libpng=1.6.22=vc14_0
- libtiff=4.0.6=vc14_2
- llvmlite=0.13.0=py35_0
- locket=0.2.0=py35_1
- lxml=3.6.4=py35_0
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_0
- menuinst=1.4.1=py35_0
- mistune=0.7.3=py35_0
- mkl=11.3.3=1
- mkl-service=1.1.2=py35_2
- mpmath=0.19=py35_1
- multipledispatch=0.4.8=py35_0
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- nbpresent=3.0.2=py35_0
- networkx=1.11=py35_0
- nltk=3.2.1=py35_0
- nose=1.3.7=py35_1
- notebook=4.2.3=py35_0
- numba=0.28.1=np111py35_0
- numexpr=2.6.1=np111py35_0
- numpy=1.11.2=py35_0
- odo=0.5.0=py35_1
- openpyxl=2.3.2=py35_0
- openssl=1.0.2j=vc14_0
- pandas=0.19.1=np111py35_0
- partd=0.3.6=py35_0
- path.py=8.2.1=py35_0
- pathlib2=2.1.0=py35_0
- patsy=0.4.1=py35_0
- pep8=1.7.0=py35_0
- pickleshare=0.7.4=py35_0
- pillow=3.3.1=py35_0
- pip=8.1.2=py35_0
- pkginfo=1.3.2=py35_0
- ply=3.9=py35_0
- prompt_toolkit=1.0.3=py35_0
- psutil=4.3.1=py35_0
- py=1.4.31=py35_0
- pyasn1=0.1.9=py35_0
- pycosat=0.6.1=py35_1
- pycparser=2.14=py35_1
- pycrypto=2.6.1=py35_4
- pycurl=7.43.0=py35_0
- pyflakes=1.3.0=py35_0
- pygments=2.1.3=py35_0
- pylint=1.5.4=py35_1
- pyodbc=3.0.10=py35_1
- pyopenssl=16.0.0=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_0
- pytables=3.2.2=np111py35_4
- pytest=2.9.2=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- pywin32=220=py35_1
- pyyaml=3.12=py35_0
- pyzmq=15.4.0=py35_0
- qt=5.6.0=vc14_0
- qtawesome=0.3.3=py35_0
- qtconsole=4.2.1=py35_2
- qtpy=1.1.2=py35_0
- requests=2.11.1=py35_0
- rope=0.9.4=py35_1
- scikit-image=0.12.3=np111py35_1
- scikit-learn=0.18=np111py35_0
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_1
- simplegeneric=0.8.1=py35_1
- singledispatch=3.4.0.3=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sockjs-tornado=1.0.3=py35_0
- sphinx=1.4.6=py35_0
- spyder=3.0.0=py35_0
- sqlalchemy=1.0.13=py35_0
- statsmodels=0.6.1=np111py35_1
- sympy=1.0=py35_0
- tk=8.5.18=vc14_0
- toolz=0.8.0=py35_0
- tornado=4.4.1=py35_0
- traitlets=4.3.0=py35_0
- unicodecsv=0.14.1=py35_0
- vs2015_runtime=14.0.25123=0
- wcwidth=0.1.7=py35_0
- werkzeug=0.11.11=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_0
- win_unicode_console=0.5=py35_0
- wrapt=1.10.6=py35_0
- xlrd=1.0.0=py35_0
- xlsxwriter=0.9.3=py35_0
- xlwings=0.10.0=py35_0
- xlwt=1.1.2=py35_0
- zlib=1.2.8=vc14_3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - dynd==c328ab7
  - et-xmlfile==1.0.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.3
  - rope-py3k==0.9.4.post1
  - tables==3.2.2
  - win-unicode-console==0.5
prefix: C:\Users\david.healey\AppData\Local\Continuum\Anaconda3\envs\hcconda

